services:
  prometheus:
    image: prom/prometheus:v3.4.0
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml
    command:
      - '--config.file=/etc/prometheus/config.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:12.0.1
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000

volumes:
  grafana-storage:
