global:
  scrape_interval: 14s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "my-app"
    static_configs:
      - targets: ["host.docker.internal:8080"]
